# Generated by Django 5.0.7 on 2024-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splitdetails',
            old_name='amount',
            new_name='amount_owed',
        ),
        migrations.AddField(
            model_name='splitdetails',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='splitdetails',
            name='status',
            field=models.CharField(default='Unpaid', max_length=50),
            preserve_default=False,
        ),
    ]
