# Generated by Django 5.0.7 on 2024-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_amount_splitdetails_amount_owed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitdetails',
            name='status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
    ]
